# Generated by Django 5.0.7 on 2024-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('buisness_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('looking_for', models.CharField(max_length=100)),
                ('service_request', models.CharField(max_length=100)),
            ],
        ),
    ]
