# Generated by Django 5.0.7 on 2024-07-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='buisness_email',
            new_name='business_email',
        ),
    ]
